// <auto-generated />
using CIDM_3312_FINAL_PROJECT_YOTAM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIDM3312FINALPROJECTYOTAM.B.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20221205030306_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("CIDM_3312_FINAL_PROJECT_YOTAM.Models.Checkout", b =>
                {
                    b.Property<int>("CheckoutID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("itemID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("totoal_price")
                        .HasColumnType("INTEGER");

                    b.HasKey("CheckoutID");

                    b.ToTable("Checkouts");
                });

            modelBuilder.Entity("CIDM_3312_FINAL_PROJECT_YOTAM.Models.cart", b =>
                {
                    b.Property<int>("CheckoutID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("itemID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("quantity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CheckoutID", "itemID");

                    b.HasIndex("itemID");

                    b.ToTable("carts");
                });

            modelBuilder.Entity("CIDM_3312_FINAL_PROJECT_YOTAM.Models.item", b =>
                {
                    b.Property<int>("itemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("item_description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("item_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("item_price")
                        .HasColumnType("INTEGER");

                    b.HasKey("itemID");

                    b.ToTable("items");
                });

            modelBuilder.Entity("CIDM_3312_FINAL_PROJECT_YOTAM.Models.cart", b =>
                {
                    b.HasOne("CIDM_3312_FINAL_PROJECT_YOTAM.Models.Checkout", "checkout")
                        .WithMany("carts")
                        .HasForeignKey("CheckoutID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CIDM_3312_FINAL_PROJECT_YOTAM.Models.item", "item")
                        .WithMany("carts")
                        .HasForeignKey("itemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("checkout");

                    b.Navigation("item");
                });

            modelBuilder.Entity("CIDM_3312_FINAL_PROJECT_YOTAM.Models.Checkout", b =>
                {
                    b.Navigation("carts");
                });

            modelBuilder.Entity("CIDM_3312_FINAL_PROJECT_YOTAM.Models.item", b =>
                {
                    b.Navigation("carts");
                });
#pragma warning restore 612, 618
        }
    }
}
